### ISSUE TITLE
observations.csv is INVALID

### ISSUE THREAD

**Issue by MartynBSpooner** [GSS-Cogs/ONS-International-Trade-in-Services#1] opened 2019-10-08 17:39 UTC
/var/jenkins_home/workspace/GSS_data/Trade/ONS-International-Trade-in-Services/out/observations.csv is INVALID
1. unmatched_foreign_key_reference. Row: 4,1. ["..."]
2. unmatched_foreign_key_reference. Row: 5,1. ["."]

**Comment by VTula2000** [comment] 2019-10-14 15:04
Foreign_keys ["..."] and  ["."] reference not available in source data

**Comment by ajtucker** [comment] 2019-10-15 16:12
Duplicate of #2

**Closed as completed by ajtucker** 2019-10-15 16:12 UTC
